apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.headlessServiceName" . }}
  labels:
    app: {{ include "proxysql.name" . }}
spec:
  clusterIP: None
  {{- if .Values.referenceStyle }}
  ports:
    - name: proxysql-admin
      port: 6032
      targetPort: 6032
      protocol: TCP
  {{- else }}
  ports:
    - port: 6032
      targetPort: controller
      protocol: TCP
      name: controller
  {{- end }}
  selector:
    app: {{ include "proxysql.name" . }}
    {{- if not .Values.referenceStyle }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- end }}
